Enable single target builds, remove maintainer build functions

diff --git a/src/jtsdk-wsjtx.in b/src/jtsdk-wsjtx.in
--- a/src/jtsdk-wsjtx.in
+++ b/src/jtsdk-wsjtx.in
@@ -25,7 +25,7 @@ set -e
 # variables passed from JTSDK Main Script
 OPT1=$1		# dev or garc...: dev = ^/dev branches, garc = ^/tags branches
 OPT2=$2		# branch name ..: ^/branches/wsjtx etc etc
-OPT3=$3		# build type....: Release, Debug, Package or Doc
+OPT3=$3		# build type ...: Release, Debug, Package, Docs, or User-Defined $VAR
 
 # set home and directory paths
 HOMEDIR=~/jtsdk
@@ -57,27 +57,64 @@ case $OPT1 in
 		OPTION=$OPT3
 		URL="https://svn.code.sf.net/p/wsjt/wsjt/branches/$OPT2"
 	;;
+
 	garc)
 		APP_SRC="$SRCD/$OPT2"
 		APP_NAME="$OPT2"
 		OPTION=$OPT3
 		URL="https://svn.code.sf.net/p/wsjt/wsjt/tags/$OPT2"
 	;;
+	
+	*)
+		clear ||:
+		echo "-------------------------------------------"
+		echo -e ${C_R} "CONFIGURATION ERROR [ $OPT1 ]"${C_NC}
+		echo "-------------------------------------------"
+		echo ''
+		echo ' COMMAND LINE USAGE'
+		echo ''
+		echo ' jtsdk-wsjtx [ $1 ] [ $2 ] [ $3 ]'
+		echo ''
+		echo ' [ $1 ] only accepts one of two arguments:'
+		echo ''
+		echo ' dev ...: designates devel branches ^/branches'
+		echo ' garc ..: designates GA and RC branches ^/tags'
+		echo ''
+		echo ' Please correct the entry, then reissue the command.'
+		echo ''
+		exit 1
+	;;
 esac
 
+# minimal arg validation
 case $OPT3 in
-	Debug)
-		DESC="Debug" ;;
-	
 	Release)
-		DESC="Release" ;;
-		
+		DESC="Release"
+	;;
+	
+	Debug)
+		DESC="Debug"
+	;;
+	
 	package)
-		DESC="Package" ;;
+		DESC="Package"
+	;;
 
-	doc)
-		OPTION="Release"
+	docs)
 		DESC="User Guide"
+	;;
+
+	*) # if $3 is NULL, set Release as default
+		if [[ -z $OPT3 ]] ; then
+			OPT3="Release"
+			DESC="Release"
+		else
+			# this has the potential to cause build failures if the target is
+			# not valid.
+			OPTION="Release"
+			DESC="$OPT3"
+		fi
+	;;
 esac
 
 
@@ -126,6 +163,19 @@ case $OPT3 in
 		echo ' * Checkout or Update WSJT-X from SVN'
 		echo ' * Configure the build'
 		echo ' * Generate the HTML document' 
+	;;
+	
+	*)
+		echo "-------------------------------------------"
+		echo -e ${C_R} "USER DEFINED TARGET [ $OPT3 ]"${C_NC}
+		echo "-------------------------------------------"
+		echo ''
+		echo ' This selection will perform the following:'
+		echo ''
+		echo ' * Checkout or Update WSJT-X from SVN'
+		echo ' * Configure the build'
+		echo " * Run the build for a single target: $OPT3"
+		echo ' * It will *NOT* install the custom target'
 	;;
 esac
 
@@ -360,6 +410,11 @@ case "$OPT3" in
 		cmake --build . --target docs  >/dev/null 2>&1
 		echo " Finnished building ..."
 	 ;;
+
+	*) # used for custom target building
+	cmake --build . --target $OPT3 -- -j "$JJ"
+	;;
+
 esac
 
 }
@@ -439,16 +494,15 @@ esac
 
 }
 
-
 # finish message ---------------------------------------------------------------
 finish_message() {
 echo ''
 echo '-----------------------------------------------------'
-echo -e ${C_G}" BUILD SUMMARY [ WSJT-X $AVER ]"${C_NC}
+echo -e ${C_G}" BUILD SUMMARY [ WSJT-X $AVER $OPT3 ]"${C_NC}
 echo '-----------------------------------------------------'
 echo ''
 case "$OPT3" in
-	Release*|Debug* )
+	Release*|Debug)
 		echo " Version ..: $AVER r$SVN_VER $BTYPE"
 		echo " SVN URL ..: $URL"
 		echo " Source ...: $APP_SRC"
@@ -466,7 +520,7 @@ case "$OPT3" in
 		echo ''
 	;;
 
-	package* )
+	package)
 		PKG_NAME=$(ls -m1 $PKGD)
 		echo " Version ...: $AVER r$SVN_VER $BTYPE"
 		echo " Name ......: $PKG_NAME"
@@ -477,10 +531,16 @@ case "$OPT3" in
 		echo ''
 	;;
 
-	doc*)
+	docs)
 		echo " Version ...: $AVER r$SVN_VER $BTYPE"
 		echo " Name ......: $FILENAME"
 		echo " Location ..: $INSTALLD/share/doc/wsjtx"
+		echo ''
+	;;
+
+	*)
+		echo " Target ..: $OPT3"
+		echo " Build ...: $BUILDD"
 		echo ''
 	;;
 esac
@@ -502,14 +562,22 @@ ug_array=('build_message' 'check_svn' 'get_app_version' 'get_svn_revision' \
 'check_separation' 'setup_dirs' 'run_cmake' 'run_build' 'run_install_build' \
 'finish_message')
 
+ud_target=('build_message' 'check_svn' 'get_app_version' \
+'get_svn_revision' 'check_separation' 'setup_dirs' 'run_cmake' 'run_build' \
+'finish_message')
 
 case $OPT3 in
 	Release|Debug|package)
-		for i in "${!build_array[@]}" ; do ${build_array[$i]} ; done					
+		for i in "${!build_array[@]}" ; do ${build_array[$i]} ; done
 	;;
+
 	doc)
-		for i in "${!ug_array[@]}" ; do ${ug_array[$i]} ; done					
+		for i in "${!ug_array[@]}" ; do ${ug_array[$i]} ; done
 	;;
+	*)
+		for i in "${!ud_target[@]}" ; do ${ud_target[$i]} ; done
+	;;
+
 esac
 
 echo ''		
diff --git a/src/jtsdk.in b/src/jtsdk.in
--- a/src/jtsdk.in
+++ b/src/jtsdk.in
@@ -53,6 +53,7 @@ C_NC='\033[01;37m'		# no color
 
 # unicode bling bling :-)
 CHK=${C_G}✔${C_NC}
+FAILED=' ✘ '
 
 ################################################################################
 #
@@ -365,10 +366,8 @@ generate_build_lists() {
 # check that each menu is present, if not, regenerate it
 if [[ ! -f $CFG/time-stamp ]] || [[ ! -f $CFG/dev_list.txt ]] || \
 [[ ! -f $CFG/ga_rc_list.txt ]] || [[ ! -f $CFG/sb_dev_list.txt ]] || \
-[[ ! -f $CFG/sb_ga_rc_list.txt ]] || [[ ! -f $CFG/maint_list.txt ]] || \
-[[ $(find $CFG/time-stamp -mmin +$GENTIME) != "" ]]
+[[ ! -f $CFG/sb_ga_rc_list.txt ]] || [[ $(find $CFG/time-stamp -mmin +$GENTIME) != "" ]]
 then
-
 	# these branches are not supported by the Superbuild script
 	dev_exclude_array=('wsjtx-1.3' 'wsjtx-1.4' 'wsjtx_k1jt_p1' 'wsjtx-superbuild' 'wsjtx_w')
 
@@ -390,10 +389,40 @@ then
 	echo ' must not be blank, and should be stated in minutes.'
 	echo ''
 	echo ' Please be patient while the update runs, this can'
-	echo ' take a few seconds depending on your internet speed'
+	echo ' take a few seconds depending on your Internet speed'
 	echo ' and access to Sourceforge'
 	echo ''
-	echo ' Contacting SourceForge'
+	# test Internet connection first
+	wget -q --tries=5 --timeout=10 -O - http://google.com > /dev/null 2>&1
+	if [[ $? -eq 0 ]]; then
+		echo -e " * Internet Connection - $CHK"
+	else
+		echo -e " * Internet Connection - $FAILED"
+		echo ''
+		echo ' You must have access to the Internet to update'
+		echo ' the WSJT-X menus. The script will continue, but'
+		echo ' you *will not* be able to update from Sourceforge'
+		echo ''
+		echo ' If you have not had a successful JTSDK update at least'
+		echo ' one time before, you may not have menu entries available'
+		echo ' for WSJT-X builds'
+		echo ''
+		read -rp "Press [ Enter ] to continue ..."
+	fi
+
+	# test access to Sourceforge WSJT SVN repository
+	svn list http://svn.code.sf.net/p/wsjt/wsjt > /dev/null 2>&1
+	if [[ $? -eq 0 ]]; then
+		echo -e " * Sourceforge Access - $CHK"
+	else
+		echo -e " * Sourceforge Access - $FAILED"
+		echo ''
+		echo ' You must have access to SF SVN repositories to update'
+		echo ' the WSJT-X menus. The script will continue, but'
+		echo ' you *will not* be able to perform updates'
+		echo ''
+		read -rp "Press [ Enter ] to continue ..."
+	fi
 
 # Generate Dev ists ------------------------------------------------------------
 	if [[ ! -f $CFG/dev_list.txt ]] || [[ ! -f $CFG/time-stamp ]] ; then
@@ -425,17 +454,6 @@ then
 	svn list "$TAGS" | grep "^wsjtx-[1-9]\.[5-9]\.[0-9]" | sed 's:/*$::' > "$TMPD"/ga_rc_list.txt
 	echo "Back-To-Main-Menu" >> "$TMPD"/ga_rc_list.txt
 	cp -u "$TMPD"/ga_rc_list.txt $CFG
-
-# Generate Maintainer List -----------------------------------------------------
-	if [[ ! -f $CFG/maint_list.txt ]] || [[ ! -f $CFG/time-stamp ]] ; then
-		UTYPE='Generating'
-	else 
-		UTYPE='Updating'
-	fi
-	echo -e " * $UTYPE Maintainer List - $CHK"
-	svn list "$TAGS" | grep "^wsjtx-[1-9]\.[5-9]\.[0-9]" | sed 's:/*$::' > "$TMPD"/maint_list.txt
-	echo "Back-To-Main-Menu" >> "$TMPD"/maint_list.txt
-	cp -u "$TMPD"/maint_list.txt $CFG
 
 # Generate Superbuild Dev List -------------------------------------------------
 	if [[ ! -f $CFG/sb_dev_list.txt ]] || [[ ! -f $CFG/time-stamp ]] ; then
@@ -490,7 +508,6 @@ wsjtx_main_menu() {
 	"1" "Development Branches" \
 	"2" "GA and RC Candidates" \
 	"3" "Superbuilds" \
-	"4" "Maintainer" \
 	"H" "Help" \
 	"B" "Back-To-Main-Menu" 2> "$TMPD"/wsjtx_menu_select
 	WSJTX_SELECT=$(head -c 1 < $TMPD/wsjtx_menu_select)
@@ -551,7 +568,7 @@ wsjtx_dev_menu() {
 		;;
 
 		3) # build the user guide
-			jtsdk-wsjtx dev "$branch" doc
+			jtsdk-wsjtx dev "$branch" docs
 		;;
 
 		4) # build the distro package
@@ -826,9 +843,6 @@ case "$MAIN_SELECT" in
 			superbuild_menu
 			continue ;;
 
-		4) # Maintainer Build Options
-			maintainer_menu
-			continue ;;
 		Back*) # do nothing, back to main menu
 			clean_tmp
 			continue ;;
